### ISSUE TITLE
Det som skal inn i "SELECT"

### ISSUE THREAD

**Issue by manjan5** [Rapporteket/smertereg#1]
Hei @areedv,
jeg ble litt usikker på hvordan jeg skulle legge inn i SELECT sammen med tabell AlleVarNum, kanskje du kan vise meg ved å legge inn det jeg skriver denne gang?
Følgende skal inkluderes:

PasientID
ForlopsID
AntTilsLege
AntTilsSykPleier
AntTilsFysioT
AntTilsPsyk
AntTilsSosio
Tilsett
InnlAvd
AntPasTils
StartdatoTO
AvdRESH

Jeg har i tillegg oppdatert R-filene og funksjonene. Så da håper jeg at alt skal være i orden.

**Comment by areedv** [comment]
Det gjør jeg. Har allerede sett litt på de funksjonene som behandler data, og det må vi gjøre noe da håndtering av csv og kobling mot kodeboken er så tett sammenvevd. Det gjelder funksjonen les_dd_oqr. Jeg begynner men kommer sikkert til å trenge hjelp...

**Comment by manjan5** [comment]
Bra! Det er bare å ta kontakt her eller på telefon angående de problemene som oppstår underveis!

**Comment by lenakba** [comment]
Hei,

Skal dette være i R-kode? Forslag:

SELECT PasientID,
ForlopsID,
AntTilsLege,
AntTilsSykPleier,
AntTilsFysioT,
AntTilsPsyk,
AntTilsSosio,
Tilsett,
InnlAvd,
AntPasTils,
StartdatoTO,
AvdRESH,
FROM AlleVarNum

Vi filtrerer på ulike kriterier i R-koden, vil det lønne seg å ha det med i
SQL-spørringa med WHERE-argument?

Med vennlig hilsen,

Lena

6. november 2017 kl. 11:46 skrev manjan5 <notifications@github.com>:

**Comment by areedv** [comment]
Jeg har allerede lagt inn spørringa, men det ser da riktig ut @lenakba. Forøvrig er det fult mulig å ha en WHERE klausul og da vil funksjonen ta inn utvalget (datointervall, sykehus, etc) som argumenter som da inngår i denne delen av spørringa. Pt tar funksjonen ingen argumenter

**Comment by manjan5** [comment]
Fungerte det som var feil hos deg @areedv når jeg nå la inn ny (gammel) kodebok?

**Comment by areedv** [comment]
Skal prøve å få testet i løpet av dagen. Sliter med dårlig samvittighet for at jeg ikke får jobbet nok med smerte...

**Comment by areedv** [comment]
Jess, din endring @manjan5 var saliggjørende. Nå er det bare resten igjen...
